services:
  planka-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: neo-planka-dev
    pull_policy: never
    command: ["bash", "-c", "npm install && npm run db:init && npm start"]
    restart: on-failure
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    ports:
      - ${SERVER_PORT:-1337}:1337
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

  planka-client:
    image: neo-planka-dev
    pull_policy: never
    command: ["bash", "-c", "npm install && npx vite --host"]
    restart: on-failure
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - ${HOST_PORT:-3000}:3000
    environment:
      - VITE_SERVER_BASE_URL=http://localhost:${SERVER_PORT:-1337}

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-planka} && psql -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-planka} -c 'SELECT 1'",
        ]
      interval: 3s
      timeout: 5s
      retries: 15
      start_period: 10s

volumes:
  db-data:
  server_node_modules:
  client_node_modules:
